### ISSUE TITLE
Inconsistent behaviour when assign same values to plain fields vs ref fields when AreFieldUpdateTriggersEnabled() == false

### ISSUE THREAD

**Issue by mnowak82** [pfusik/sooda#2]
When user updates plain fields with AreFieldUpdateTriggersEnabled() == false using the same value
Sooda generates update for that field and invokes Before/AfterObjectUpdate (other fields are unchanged). When using reference value it doesn't do that (no update and no invoke).

Regards,
Maciek

**Comment by pfusik** [comment]
There's an "optimization" for plain fields that avoids database reads when updating fields. E.g.

    Foo o = Foo.GetRef(42); // no SELECT if no polymorphism
    o.Bar = 5; // causes UPDATE Foo SET bar = 5 on commit

This is not done for reference fields because they can be 1-N foreign keys, e.g.

    Foo o = Foo.GetRef(42);
    o.Parent = Quux.GetRef(5); // potentially affects two Quux.Children collections - remove from the old one and add to the new one

The only good fix is see to remove this "optimization" for plain fields, i.e. always check the old value.
